### ISSUE TITLE
How do I remove /src/www/ from links?

### ISSUE THREAD

**Issue by htorbov** [isohuntto/openbay#128]
On every link I see /src/www/ - how do I remove it?
I guess with .htaccess?

**Comment by TheChiefCoC** [comment]
no you need to modify the apache virtualhost file that is found in /etc/apache2/sites-available/xxx.conf [xxx being the name of your virutal host file name]
refer to this : https://ghostbin.com/paste/djvbq

**Comment by nexusrain** [comment]
Yea, by setting the document root or just root when using nginx into the www folder. See my guide, here: https://www.bitforce.io/hacking/howto-setup-openbay-on-debian-ubuntu-with-nginx-1-6-2/
