### ISSUE TITLE
No shows me the installation page.

### ISSUE THREAD

**Issue by kinocalde** [isohuntto/openbay#172]
1- I upload files to the server.
2- Then I create a new database.
3- When I try to enter the main domain for the installation, only shows me the "index of"

Help...

**Comment by TPBT-OFFICIAL** [comment]
You do know isohunt changed the whole code, you need your own vps or dedicated servers to hos it, not shared hosting.

**Comment by kinocalde** [comment]
Oh, thanks, suspected that but was not sure. Thanks for the information.
