### ISSUE TITLE
GitTorrent

### ISSUE THREAD

**Issue by borissmidt** [isohuntto/openbay#22]
Maybe this project can be made even more distributed and anonymous by using the git torrent protocol. However i do not know how far the gitTorrent project is developed and how stable it is. 
http://advogato.org/article/994.html
It probably needs some extra work. But it might be a good backup when this repository gets banned from github.

**Comment by borissmidt** [comment]
I'm happy to know there are many options. Hopefully in the future we will have a good way to share P2P with updates like git.

**Comment by GreenLunar** [comment]
It's possible via IPFS.  Best mass-scaled implementation of P2P-Web so far.
Websites, blogs, cloud, git, file sharing, just name it
